In [2]:
# Part 1 - Building the CNN
# Importing the Keras libraries and packages
#import keras
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [45]:
# Initialising the CNN
classifier = Sequential()

In [46]:
# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

In [47]:
# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

#classifier.add(Dropout(0.25))

In [48]:
# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

In [49]:
# Step 3 - Flattening
classifier.add(Flatten())

In [50]:
# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
#classifier.add(Dropout(0.25))
classifier.add(Dense(units = 1, activation = 'sigmoid'))


In [71]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_18 (Conv2D)           (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_19 (Conv2D)           (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 6272)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 128)               802944    
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 129       
Total para

In [51]:
# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [54]:
# Part 2 - Fitting the CNN to the images

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('C:/Users/epatdeb/TensorFlow_Project_1/CNN_CatsDogs/Pets_cnn/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')
test_set = test_datagen.flow_from_directory('C:/Users/epatdeb/TensorFlow_Project_1/CNN_CatsDogs/Pets_cnn/test_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')


Found 19998 images belonging to 2 classes.
Found 4998 images belonging to 2 classes.


In [55]:
# I have already run the training model as it take some time. Original epoch #25
classifier.fit_generator(training_set,
                         steps_per_epoch = 19998,
                         epochs = 2, 
                         validation_data = test_set,
                         validation_steps = 4998)



Epoch 1/2
   11/19998 [..............................] - ETA: 8815s - loss: 0.0093 - acc: 0.9943

C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 80000 bytes but only got 0. Skipping tag 64640
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 6553600 bytes but only got 0. Skipping tag 49
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1050744 bytes but only got 4951. Skipping tag 51
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 293339136 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(

  169/19998 [..............................] - ETA: 5915s - loss: 0.0038 - acc: 0.9991

C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 209715200 bytes but only got 0. Skipping tag 48
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 52428800 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 6468665344 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1050744 bytes but only got 7027. Skipping tag 48
  " Skipping tag %s" % (size, le

  182/19998 [..............................] - ETA: 5944s - loss: 0.0039 - acc: 0.9991

C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 32 bytes but only got 0. Skipping tag 270
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 5 bytes but only got 0. Skipping tag 271
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 0. Skipping tag 272
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 0. Skipping tag 282
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\ep

  483/19998 [..............................] - ETA: 6116s - loss: 0.0161 - acc: 0.9939

C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 404094976 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 404619264 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 425459712 bytes but only got 0. Skipping tag 4
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385474 bytes but only got 6833. Skipping tag 513
  " Skipping tag %s" % (size, le

  487/19998 [..............................] - ETA: 6110s - loss: 0.0161 - acc: 0.9939

C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 18350080 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:709: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 6. 
  warnings.warn(str(msg))


  530/19998 [..............................] - ETA: 6078s - loss: 0.0181 - acc: 0.9933

C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 262146 bytes but only got 0. Skipping tag 2
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 262151 bytes but only got 0. Skipping tag 56
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:709: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 0. 
  warnings.warn(str(msg))


  579/19998 [..............................] - ETA: 6058s - loss: 0.0199 - acc: 0.9927

C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 307363840 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 307888128 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 328728576 bytes but only got 0. Skipping tag 4
  " Skipping tag %s" % (size, len(data), tag))
C:\Users\epatdeb\AppData\Local\conda\conda\envs\py36\lib\site-packages\PIL\TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385474 bytes but only got 5357. Skipping tag 513
  " Skipping tag %s" % (size, le

19998/19998 [==============================] - 16766s - loss: 0.0138 - acc: 0.9956 - val_loss: 1.6854 - val_acc: 0.7879
Epoch 2/2
19998/19998 [==============================] - 48827s - loss: 0.0044 - acc: 0.9987 - val_loss: 1.9599 - val_acc: 0.7857


In [1]:
# Part 3 - Making new predictions
test_image = keras.preprocessing.image.load_img('C:/Users/epatdeb/TensorFlow_Project_1/CNN_CatsDogs/Pets_cnn/predict/c_5.jpg',target_size = (300, 300)) #
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
%matplotlib inline
#plt.figure(1)
plt.imshow(test_image)


NameError: name 'keras' is not defined

In [60]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('C:/Users/epatdeb/TensorFlow_Project_1/CNN_CatsDogs/Pets_cnn/predict/c_5.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
print (np.shape(test_image))
print ("*****************")
test_image = np.expand_dims(test_image, axis = 0)
print (test_image)
result = classifier.predict(test_image)
print ("**********************")
print (result)
print ("**********************")
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
prediction

(64, 64, 3)
*****************
[[[[  42.    6.    8.]
   [  57.    1.   10.]
   [  73.    0.   12.]
   ..., 
   [  80.   73.   65.]
   [  75.   70.   64.]
   [  71.   66.   62.]]

  [[  58.    0.    7.]
   [  80.    2.   18.]
   [ 100.    7.   26.]
   ..., 
   [  77.   68.   61.]
   [  73.   66.   60.]
   [  69.   61.   58.]]

  [[  90.    3.   22.]
   [ 107.    7.   31.]
   [ 122.   12.   37.]
   ..., 
   [  58.   47.   41.]
   [  54.   45.   40.]
   [  51.   41.   39.]]

  ..., 
  [[ 103.   97.   97.]
   [ 187.  183.  182.]
   [ 197.  196.  194.]
   ..., 
   [ 154.  157.  162.]
   [ 155.  158.  163.]
   [ 157.  160.  165.]]

  [[  95.   89.   89.]
   [ 185.  181.  180.]
   [ 196.  195.  193.]
   ..., 
   [ 157.  160.  165.]
   [ 155.  158.  163.]
   [ 152.  155.  160.]]

  [[  83.   77.   77.]
   [ 180.  176.  175.]
   [ 194.  193.  191.]
   ..., 
   [ 161.  164.  169.]
   [ 155.  158.  163.]
   [ 145.  148.  153.]]]]
**********************
[[ 0.]]
**********************


'cat'

In [58]:
training_set.class_indices

{'Cat': 0, 'Dog': 1}

In [70]:
def softmax(X):
    exps = np.exp(X)
    return exps / np.sum(exps)

s8 = softmax([2, 3, 1, 5])
print (s8)

[ 0.0413707   0.11245721  0.01521943  0.83095266]
